dist: xenial
language: go
go:
  - "1.11.x"

matrix:
  include:
    - os: linux
      services:
        - docker
    - os: osx
      osx_image: xcode8

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test;
    sudo apt-get update -qq;
    fi

env:
  global:
    - ELECTRON_CACHE: $HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE: $HOME/.cache/electron-builder

cache:
  directories:
    - node_modules
    - electron/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds

services:
  - xvfb

addons:
  chrome: stable

install:
  - nvm install 10.15
  - nvm use 10.15
  - if [[ ! -d "$GOPATH/src/github.com/skycoin/skycoin-web" ]]; then
    mkdir -p $GOPATH/src/github.com/skycoin;
    ln -s $TRAVIS_BUILD_DIR $GOPATH/src/github.com/skycoin/skycoin-web;
    fi
  - cd $GOPATH/src/github.com/skycoin/skycoin-web
  - make install-deps-ui


before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TRAVIS_PULL_REQUEST" == false ]]; then ./ci-scripts/add-key.sh; fi

script:
  # Run 'check' on linux, as osx does not have `docker` service.
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make check; fi || exit 1
  - make lint || exit 1
  - make unit-test || exit 1
  # Do not do code signing if it's a PR.
  - if [[ "$TRAVIS_PULL_REQUEST" == true && "$TRAVIS_OS_NAME" == "osx" ]]; then
      CSC_IDENTITY_AUTO_DISCOVERY=false make build-electron || exit 1;
    else
      make build-electron || exit 1;
    fi

notifications:
  email:
    - travis@skuycoin.net
  # https://github.com/kvld/travisci-telegram TravisCI Telegram Bot integration
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $AWS_BUCKET
  skip_cleanup: true
  local_dir: electron/release
  upload-dir: wallet-lite
  acl: public_read
  region: $AWS_REGION
  on:
    repo: skycoin/skycoin-web
    tags: true
